### ISSUE TITLE
Not able to use unity-catalog in spark job

### ISSUE THREAD

**Issue by tpang-cxl** [unitycatalog/unitycatalog#143]
Could someone help on how to get unity catalog to work in a spark job?

after I start the unity catalog server on my laptop, I created my spark session with below code:
`
    conf.set('spark.sql.extensions', 'io.delta.sql.DeltaSparkSessionExtension')
    conf.set(f'spark.sql.catalog.unity', 'org.apache.spark.sql.delta.catalog.DeltaCatalog')
    conf.set(f'spark.sql.catalog.unity.uri', 'http://localhost:8080/api/2.1/unity-catalog/')
    conf.set(f'spark.sql.catalog.unity.type', 'rest')
    conf.set('spark.databricks.sql.initial.catalog', 'unity')
    conf.set('spark.sql.warehouse.dir', f's3a://aaa/main/warehouse')
    conf.set('fs.s3a.access.key', ACCESS_KEY)
    conf.set('fs.s3a.secret.key', SECRET_KEY)
    session = SparkSession.builder.config(conf=conf) \
        .getOrCreate()

    session.sql(f"USE CATALOG 'unity'")
`

I got the following error:
Traceback (most recent call last):
  File "/Users/xxx/tmp/images/unity-catalog/main.py", line 98, in <module>
    spark = create_spark_session()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/tmp/images/unity-catalog/main.py", line 77, in create_spark_session
    session.sql(f"USE CATALOG 'unity'")
  File "/Users/xxx/anaconda3/envs/pyspark-3.5/lib/python3.11/site-packages/pyspark/sql/session.py", line 1631, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/anaconda3/envs/pyspark-3.5/lib/python3.11/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
                   ^^^^^^^^^^^^^^^^^
  File "/Users/xxx/anaconda3/envs/pyspark-3.5/lib/python3.11/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.ParseException:
[PARSE_SYNTAX_ERROR] Syntax error at or near ''unity'': extra input ''unity''.(line 1, pos 12)

**Comment by MrPowers** [comment]
We're working on this, see [this PR](https://github.com/unitycatalog/unitycatalog/pull/132) 🤓.

**Comment by jaceklaskowski** [comment]
IMHO `DeltaCatalog` does not support any of the provided params (they seem like "borrowed" from an [Iceberg-based setup](https://tabular.io/apache-iceberg-cookbook/getting-started-connect-rest-catalog/)).

**Comment by tpang-cxl** [comment]
Thanks for all the responses. Any progress on this issue @MrPowers ?

**Comment by tpang-cxl** [comment]
@MrPowers , I saw a new connectors module was added to the repo. But it seems to have the following problems:

1. The spark connector use Scala 2.13 and Spark-sql 4.0.0 preview version. DO you have plan to add Scala 2.12 support and Spark 3.3, 3.4 and 3.5? Even though Spark 4.0 may backward compatible with Spark 3.x, but it does reduce the confidence level, especially with a preview version. Similarly for the scala version, it will be great if you can confirm the connector works both with Scala 2.12 and 2.13. **This would be more important for Pyspark developers, since so far Pypi's pyspark is still on Scala 2.12**
2. There seems no document for the new connector module(forgive me if I missed out). I went into the test and see how spark session should be created, still, it would be much better to have full/detailed document about how the connector should be used
Thanks for your help

**Comment by ravivj-db** [comment]
@cloud-fan can you assign this to yourself please.

**Comment by cloud-fan** [comment]
I can't update the `Assignees` field. Maybe only the repo owner can do so?

**Comment by MrPowers** [comment]
@cloud-fan - assigned this one to you.  Thanks for working on this 🤓

**Comment by cloud-fan** [comment]
it will be supported in the upcoming UC v0.2 release
