### ISSUE TITLE
Caused by: io.unitycatalog.client.ApiException: listCatalogs call failed with: 404

### ISSUE THREAD

**Issue by schobe** [unitycatalog/unitycatalog#25]
Hi,

After starting the UC server, the list catalogs command is failing with following error. 

% bin/uc catalog list
Exception in thread "main" java.lang.RuntimeException: io.unitycatalog.client.ApiException: listCatalogs call failed with: 404 - 

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Airflow 404</title>
    <link rel="icon" type="image/png" href="/static/pin_32.png">
  </head>
  <body>
    <div style="font-family: verdana; text-align: center; margin-top: 200px;">
      <img src="/static/pin_100.png" width="50px" alt="pin-logo" />
      <h1>Airflow 404</h1>
      <p>Page cannot be found.</p>
      <a href="/">Return to the main page</a>
      <p>redact</p>
    </div>
  </body>
</html>
        at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:98)
Caused by: io.unitycatalog.client.ApiException: listCatalogs call failed with: 404 - 

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Airflow 404</title>
    <link rel="icon" type="image/png" href="/static/pin_32.png">
  </head>
  <body>
    <div style="font-family: verdana; text-align: center; margin-top: 200px;">
      <img src="/static/pin_100.png" width="50px" alt="pin-logo" />
      <h1>Airflow 404</h1>
      <p>Page cannot be found.</p>
      <a href="/">Return to the main page</a>
      <p>redact</p>
    </div>
  </body>
</html>
        at io.unitycatalog.client.api.CatalogsApi.getApiException(CatalogsApi.java:77)
        at io.unitycatalog.client.api.CatalogsApi.listCatalogsWithHttpInfo(CatalogsApi.java:356)
        at io.unitycatalog.client.api.CatalogsApi.listCatalogs(CatalogsApi.java:333)
        at io.unitycatalog.cli.CatalogCli.listCatalogs(CatalogCli.java:61)
        at io.unitycatalog.cli.CatalogCli.handle(CatalogCli.java:37)
        at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:73)

**Comment by schobe** [comment]
Airflow was running on local server. I stopped airflow server and it worked after that.
