### ISSUE TITLE
Failed to read delta table (local file)

### ISSUE THREAD

**Issue by salman2learn** [unitycatalog/unitycatalog#348]
A delta folder with sample data is created by deltalake python package. Duckdb can read it properly, but uc cannot.

```sh
./duckdb -c "select * from delta_scan('data2/datadelta')"
┌───────┬─────────┬──────────────────────────┐
│  id   │  name   │           dob            │
│ int64 │ varchar │ timestamp with time zone │
├───────┼─────────┼──────────────────────────┤
│     1 │ john    │ 2023-12-31 18:00:00-06   │
│     2 │ jane    │ 2024-02-01 18:00:00-06   │
│     3 │ jill    │ 2024-03-02 18:00:00-06   │
│     4 │ jack    │ 2024-04-03 19:00:00-05   │
└───────┴─────────┴──────────────────────────┘
```

Open source unity catalog is able to register the table, but not able to query it.
```sh
bin/uc table create --full_name unity.default.data --storage_location "/home/user1/work/unitycatalog/data2/datadelta" --columns "id INT, name STRING, dob DATE" --format DELTA 
```

```sh
bin/uc table read --full_name unity.default.data
Error occurred while executing the command. Failed to read delta table file:///home/user1/work/unitycatalog/data2/datadelta/Failed to read delta table
```

**Comment by salman2learn** [comment]
Thanks. I was able to make it run after removing dob (timestamp) column. 
Do you know the correct datatype to specify for the timestamp column? Apparently DATE is not mapping to it.

**Comment by VillePuuska** [comment]
I tested this in a fresh codespace and TIMESTAMP seems to work. My steps:

Create/register the table in UC and check the CLI can read the empty table

    bin/uc table create --full_name unity.default.data --storage_location "/workspaces/unitycatalog/test_delta_tbl" --columns "id INT, name STRING, dob TIMESTAMP" --format DELTA
    bin/uc table read --full_name unity.default.data

Output:

    ┌──────────────────────────┬─────────────────────────┬─────────────────────────┐
    │id(integer)               │name(string)             │dob(timestamp)           │
    └──────────────────────────┴─────────────────────────┴─────────────────────────┘

Write the sample data to the table with Polars/delta-rs

    import polars as pl
    
    df = pl.DataFrame(
        {
            "id": [1, 2, 3, 4],
            "name": ["john", "jane", "jill", "jack"],
            "dob": [
                "2023-12-31T18:00:00-0600",
                "2024-02-01T18:00:00-0600",
                "2024-03-02T18:00:00-0600",
                "2024-04-03T19:00:00-0500",
            ],
        }
    ).with_columns(pl.col("dob").str.to_datetime())
    
    df.write_delta(target="/workspaces/unitycatalog/test_delta_tbl", mode="append")

Read the table with the CLI again

    bin/uc table read --full_name unity.default.data

Output:

    ┌──────────────────────────┬─────────────────────────┬─────────────────────────┐
    │id(integer)               │name(string)             │dob(timestamp)           │
    ├──────────────────────────┼─────────────────────────┼─────────────────────────┤
    │1                         │john                     │2024-01-01T00:00         │
    ├──────────────────────────┼─────────────────────────┼─────────────────────────┤
    │2                         │jane                     │2024-02-02T00:00         │
    ├──────────────────────────┼─────────────────────────┼─────────────────────────┤
    │3                         │jill                     │2024-03-03T00:00         │
    ├──────────────────────────┼─────────────────────────┼─────────────────────────┤
    │4                         │jack                     │2024-04-04T00:00         │
    └──────────────────────────┴─────────────────────────┴─────────────────────────┘

Check that DuckDB can read the table

    ./duckdb -c "select * from delta_scan('test_delta_tbl')"

Output:
    
    ┌───────┬─────────┬─────────────────────┐
    │  id   │  name   │         dob         │
    │ int32 │ varchar │      timestamp      │
    ├───────┼─────────┼─────────────────────┤
    │     1 │ john    │ 2024-01-01 00:00:00 │
    │     2 │ jane    │ 2024-02-02 00:00:00 │
    │     3 │ jill    │ 2024-03-03 00:00:00 │
    │     4 │ jack    │ 2024-04-04 00:00:00 │
    └───────┴─────────┴─────────────────────┘

Note that with these steps the timezones aren't present anymore. The issue you're running into probably has to do with the timezones in the timestamps, but idk what the issue actually is or how to repro it. 🤔

**Comment by dennyglee** [comment]
Thanks a bunch, @VillePuuska  - I really appreciate the dive into it!

Timestamps are always a doozy, so there may be some explicit datatype conversions required here. @salman2learn, is there any chance we can get a repro so we can reproduce the issue?   As well, which version of `delta-rs` are you using as I recall some issues related to `pyarrow` versions in the past but that may be a red herring hence the exact repo steps and versions you're using. Thanks!

**Comment by vksx** [comment]
@VillePuuska Your code works with `DATE` as well: `--columns "id INT, name STRING, dob DATE"`.

id(integer) | name(string) | dob(date)*
------|---|------
 1 | john | 2024-01-01
2  | jane | 2024-02-02
3  | jill    | 2024-03-03
4  | jack | 2024-04-04  

_*These values are localized to the 'Asia/Kolkata' timezone._

But, it is unable to create the table with `TIMESTAMP_NTZ`:
```text
bin/uc table create --full_name unity.default.data3 --storage_location "/path/to/test_delta_tbl3" --columns "id INT, name STRING, dob TIMESTAMP_NTZ" --format DELTA
Error occurred while executing the command. Failed to create delta table at /path/to/test_delta_tbl3Failed to create delta table
```
Creating a table with column type `TIMESTAMP_NTZ` is not working properly - even though it is present in the [API spec](https://github.com/unitycatalog/unitycatalog/blob/a28ec6f8974a04e5fbde25ceff5eef102938c0ab/api/all.yaml#L1151).

**Comment by VillePuuska** [comment]
Good catch @vksx Looks like the delta kernel does not support writing data of type `TIMESTAMP_NTZ`. Adding throwing the exception to the main of the CLI gives you

    Exception in thread "main" io.unitycatalog.cli.utils.CliException: Failed to create delta table at /tmp/asdtable2
            at io.unitycatalog.cli.TableCli.handleTableStorageLocation(TableCli.java:129)
            at io.unitycatalog.cli.TableCli.createTable(TableCli.java:96)
            at io.unitycatalog.cli.TableCli.handle(TableCli.java:43)
            at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:101)
    Caused by: java.lang.IllegalArgumentException: Failed to create delta table
            at io.unitycatalog.cli.delta.DeltaKernelUtils.createDeltaTable(DeltaKernelUtils.java:52)
            at io.unitycatalog.cli.TableCli.handleTableStorageLocation(TableCli.java:123)
            ... 3 more
    Caused by: io.delta.kernel.exceptions.KernelException: Kernel doesn't support writing data of type: timestamp_ntz
            at io.delta.kernel.internal.DeltaErrors.unsupportedDataType(DeltaErrors.java:138)
            ...

If I'm not completely mistaken, the relevant code in delta kernel is
https://github.com/delta-io/delta/blob/a7450003327a41414ca320aca7f610d18a92a3bb/kernel/kernel-api/src/main/java/io/delta/kernel/internal/DeltaErrors.java#L137
and
https://github.com/delta-io/delta/blob/a7450003327a41414ca320aca7f610d18a92a3bb/kernel/kernel-api/src/main/java/io/delta/kernel/internal/util/SchemaUtils.java#L246

**Comment by MrPowers** [comment]
Cool, looks like this is resolved for now.  Everything should work once Delta Kernel supports `TIMESTAMP_NTZ`.

Engines that support `TIMESTAMP_NTZ` should be able to read that columns.
