### ISSUE TITLE
Quickstart Guide errors on Mac

### ISSUE THREAD

**Issue by ryanturnberry** [unitycatalog/unitycatalog#395]
**Describe the bug**

From a fresh git clone of the repo and following the quickstart guide, running the command `bin/uc table list --catalog unity --schema default` causes this error:

`Exception in thread "main" java.lang.RuntimeException: io.unitycatalog.client.ApiException: getTable call failed with: 404 - {
"servlet":"org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-17f62e33",
"message":"Not Found",
"url":"/api/2.1/unity-catalog/tables/unity.default.numbers",
"status":"404"
}
	at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:127)
Caused by: io.unitycatalog.client.ApiException: getTable call failed with: 404 - {
"servlet":"org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-17f62e33",
"message":"Not Found",
"url":"/api/2.1/unity-catalog/tables/unity.default.numbers",
"status":"404"
}
	at io.unitycatalog.client.api.TablesApi.getApiException(TablesApi.java:76)
	at io.unitycatalog.client.api.TablesApi.getTableWithHttpInfo(TablesApi.java:263)
	at io.unitycatalog.client.api.TablesApi.getTable(TablesApi.java:241)
	at io.unitycatalog.cli.TableCli.readTable(TableCli.java:162)
	at io.unitycatalog.cli.TableCli.handle(TableCli.java:52)
	at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:101)`

**To Reproduce**

On a macbook:

1. Clone the repository.

2. Ensured the JAVA_HOME environment variable your terminal is configured to point to JDK17.

> echo $JAVA_HOME = /Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home

3. Compile the project using `build/sbt package`

4. Run the server using: `bin/start-uc-server`

5. Switch to a new terminal and run `bin/uc table list --catalog unity --schema default`

I get an error that says:
Exception in thread "main" java.lang.RuntimeException: io.unitycatalog.client.ApiException: listTables call failed with: 404

**Expected behavior**

Following the quickstart guide on mac should allow the project to work

**System [please complete the following information]:**

-   OS: macOS Sonoma 14.4

**Additional context**

**Comment by jaceklaskowski** [comment]
take

**Comment by IainMeeke** [comment]
seeing the same issue. I'm also on Mac M1 Pro running Sonoma 14.3 and Java 17

**Comment by vksx** [comment]
I tried to reproduce this on my end (Sonoma 14.5) with a fresh clone - followed all the steps mentioned - and it's working fine. Are you sure the environment is correctly set in your case?

More context:

Java executable location:
```zsh
> which java
/usr/bin/java
```
Java version:
```zsh
> java -version
openjdk version "17.0.12" 2024-07-16 LTS
OpenJDK Runtime Environment Corretto-17.0.12.7.1 (build 17.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.12.7.1 (build 17.0.12+7-LTS, mixed mode, sharing)
```
JAVA_HOME Path (Java installation):
```zsh
> /usr/libexec/java_home
/Users/vikas/Library/Java/JavaVirtualMachines/corretto-17.0.12/Contents/Home
```
`.zshrc` configuration:
```zsh
> nano ~/.zshrc
export PATH="/opt/homebrew/bin:$PATH"
```

**Comment by IainMeeke** [comment]
``` 
> java -version
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Homebrew (build 17.0.11+0)
OpenJDK 64-Bit Server VM Homebrew (build 17.0.11+0, mixed mode, sharing)
```

I also added homebrew to the path like you did. Still getting that issue.

**Comment by MrPowers** [comment]
@jaceklaskowski - any updates on this one?

**Comment by gardnmi** [comment]
Just to pile on.  The quickstart says you need Java 11 and you get a Java 17 or above is required error when runng `bin/start-uc-server`

![image](https://github.com/user-attachments/assets/c3ce6161-07ee-4336-9b79-dd3f39a749f1)
![image](https://github.com/user-attachments/assets/5791d6c3-90d0-47fd-8725-91adc68ffce0)

**Comment by Venkata-Manideep** [comment]
any update on this issue ?
