### ISSUE TITLE
Writes to databricks Unity Catalog from local spark not working

### ISSUE THREAD

**Issue by ranjitha-shenoy** [unitycatalog/unitycatalog#560]
**Describe the bug**

**To Reproduce**

1. Create local spark session 
```
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local").
appName("Word Count")
.config("spark.jars.packages", "org.apache.hadoop:hadoop-aws:3.3.4,io.delta:delta-spark_2.12:3.2.1,io.unitycatalog:unitycatalog-spark_2.12:0.2.0")
.config("spark.sql.extensions","io.delta.sql.DeltaSparkSessionExtension")
.config("spark.sql.catalog.<catalog_name>","io.unitycatalog.spark.UCSingleCatalog")
.config("spark.sql.catalog.<catalog_name>.uri","https://<workspace_url>/api/2.1/unity-catalog")
.config("spark.sql.catalog.<catalog_name>.token","<token>")
.config("spark.hadoop.fs.s3.impl","org.apache.hadoop.fs.s3a.S3AFileSystem")
.config("spark.sql.catalog.spark_catalog","org.apache.spark.sql.delta.catalog.DeltaCatalog")
.config("spark.sql.defaultCatalog","<catalog_name>").getOrCreate()
```
2. Reads are working 
```spark.sql("select * from <schema>.<table> limit 10").show()```
3. Trying to write 
```
spark.sql("""CREATE TABLE <schema>.<table> (id INT, desc STRING) USING delta LOCATION 's3://<bucket>/<prefix>
```
fails with 
```
: io.unitycatalog.client.ApiException: generateTemporaryPathCredentials call failed with: 401 - {"error_code":"UNAUTHENTICATED","message":"Request to generate access credential for path 's3://<bucket>/<prefix>' from outside of Databricks Unity Catalog enabled compute environment is denied for security. Please contact Databricks support for integrations with Unity Catalog.","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"UNITY_CATALOG_EXTERNAL_GENERATE_PATH_CREDENTIALS_DENIED","domain":"unity-catalog.databricks.com","metadata":{"path":"s3://<bucket>/<prefix>}},{"@type":"type.googleapis.com/google.rpc.RequestInfo","request_id":"<request_id>","serving_data":""}]}
	at io.unitycatalog.client.api.TemporaryCredentialsApi.getApiException(TemporaryCredentialsApi.java:78)
	at io.unitycatalog.client.api.TemporaryCredentialsApi.generateTemporaryPathCredentialsWithHttpInfo(TemporaryCredentialsApi.java:192)
	at io.unitycatalog.client.api.TemporaryCredentialsApi.generateTemporaryPathCredentials(TemporaryCredentialsApi.java:170)
	at io.unitycatalog.spark.UCSingleCatalog.createTable(UCSingleCatalog.scala:106)
	at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:44)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
```
4. Same user token can create tables/write to existing tables from databricks workspace using DBSQL
**Expected behavior**

Writes from local spark to databricks UC works with AWS S3 external tables

-   OS: e.g. [Ubuntu 18.04]

pip install pyspark==3.5.3

**Comment by victoria-db** [comment]
ahoy, thank you for this question. 

You are running into a specific Databricks Unity Catalog quirk. DBX UC governs `EXTERNAL_LOCATIONS` for users. The result is that for create a table the user requires `CREATE EXTERNAL TABLE` on the external storage location, as well as the catalog privileges `USE CATALOG` and `USE SCHEMA`.

Once those are enabled you will be able to create a table. Once the table is created, to write you only need `USE CATALOG` and `USE SCHEMA`. Once the table is created access to storage can be granted through catalog privliages alone.

**Comment by ranjitha-shenoy** [comment]
Hi @victoria-db thank you for answering.

I am able to create the table and insert/write from within the databricks workspace using db-sql endpoint with same user whose databricks api token I am using in the local spark setup. 
If I was missing any permissions wouldn't I receive an error from db-sql as well complaining of insufficient permissions. 
Are there any additional permissions specific to accessing from outside the databricks workspace?

**Comment by victoria-db** [comment]
The other issue could be that your Databricks account has not enabled the feature flag to expose `generateTemporaryPathCredentials.` I recommend contacting your Databricks account team to see what needs to be enabled to get this working on your account. From the OSS Spark side, it looks like you are doing everything correctly, and the error is coming from the Databricks Unity Catalog.

**Comment by cpbotha** [comment]
I have just run into the same issue.

As a test, I granted the user account in question `ALL PRIVILEGES` on the containing external location, but I'm still getting the same error when attempting to create the external table.

It looks like the `generateTemporaryPathCredentials` endpoint itself is responding with the message that it's denying my request.

```
io.unitycatalog.client.ApiException: generateTemporaryPathCredentials call failed with: 401 - {"error_code":"UNAUTHENTICATED","message":"Request to generate access credential for path 'abfss://containerXYZ@storageAccXYZ.dfs.core.windows.net/prod' from outside of Databricks Unity Catalog enabled compute environment is denied for security. Please contact Databricks support for integrations with Unity Catalog.","details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"UNITY_CATALOG_EXTERNAL_GENERATE_PATH_CREDENTIALS_DENIED","domain":"unity-catalog.databricks.com","metadata":{"path":"abfss://containerXYZ@storageAccXYZ.dfs.core.windows.net/somedir"}},{"@type":"type.googleapis.com/google.rpc.RequestInfo","request_id":"e4be9d83-9e3e-47d9-bc04-1ad3f4c89ec5","serving_data":""}]}
```

**Comment by dipankarkush-db** [comment]
Hi @cpbotha - Thanks for your post. Yes, you would need a SAFE Flag to be enabled for the workspace for you to achieve this. Until that time, can you please create the external table from the Databricks Workspace and modify the table from external engine. You can work with your Databricks Point of Contact to get help on enabling the SAFE flag for the workspace.

**Comment by cpbotha** [comment]
Much appreciated, thank you @dipankarkush-db !

**Comment by dixonantony** [comment]
@dipankarkush-db , where exactly is the SAFE flag to be enabled?

**Comment by claudiazi** [comment]
@ranjitha-shenoy  did it work for you to create a managed table on unity catalog?
even te managed table is not working for me with error that the schema doesnt exist (although it does exist)

**Comment by Yogi776** [comment]
---

### **Title**

`PERMISSION_DENIED: User lacks EXTERNAL USE SCHEMA on 'icebase.telemetry' while reading table`

---

### **Description**

When attempting to read a Unity Catalog table from Databricks using PySpark, the following error is thrown:

```
io.unitycatalog.client.ApiException: generateTemporaryTableCredentials call failed with: 403 - 
{"error_code":"PERMISSION_DENIED",
 "message":"User does not have EXTERNAL USE SCHEMA on Schema 'icebase.telemetry'.",
 "details":[
   {"@type":"type.googleapis.com/google.rpc.ErrorInfo",
    "reason":"PERMISSION_DENIED",
    "domain":"unity-catalog.databricks.com",
    "metadata":{"principalName":"User","msg":"EXTERNAL USE SCHEMA","resourceType":"Schema","resourceName":"icebase.telemetry"}},
   {"@type":"type.googleapis.com/google.rpc.RequestInfo",
    "request_id":"bd9d1fb5-f1a5-4b74-a0fa-03aa01e3c900","serving_data":""}
 ]}
```

---

### **Steps to Reproduce**

1. Start a local PySpark session with Unity Catalog configured using:

   ```python
   UC_CATALOG = "icebase"
   UC_SCHEMA = "telemetry"
   UC_TABLE = "device"
   ```
2. Authenticate using a valid Databricks **Personal Access Token**.
3. Attempt to run:

   ```python
   spark.sql("SELECT * FROM icebase.telemetry.device LIMIT 5")
   ```

---

### **Expected Behavior**

The query should read the table data and return results without permission issues.

---

### **Actual Behavior**

The process fails with a `PERMISSION_DENIED` error, indicating the user does not have **EXTERNAL USE SCHEMA** privileges for the schema `icebase.telemetry`.

---

### **Environment Details**

* **Databricks Workspace URL:** `https://dbc-983c7c06-7c80.cloud.databricks.com`
* **Catalog/Schema/Table:** `icebase.telemetry.device`
* **spark.sql.defaultCatalog:** `icebase`
* **Libraries Used:**

  * `hadoop-aws:3.3.4`
  * `delta-spark_2.12:3.2.1`
  * `unitycatalog-spark_2.12:0.2.0`
* **Execution Mode:** Local PySpark (`master=local[*]`)

---

### **Suggested Resolution**

* Grant the user the missing permission with:

  ```sql
  GRANT EXTERNAL USE SCHEMA ON SCHEMA icebase.telemetry TO `your-user`;
  ```
* Or confirm that the current user has at least **USE SCHEMA** and **SELECT** permissions.

---
