### ISSUE TITLE
BUG: problem: Unexpected value 'VIEW'

### ISSUE THREAD

**Issue by dmoore247** [unitycatalog/unitycatalog#657]
**Describe the bug**

Error when listing a (Databricks managed UC Catalog) schema that contains a VIEW.

**To Reproduce**

1. `git pull`
2. `bin/uc table list --catalog douglas_moore --schema demo --server https://adb-984752964297111.11.azuredatabricks.net --auth_token $TOKEN`

```
Exception in thread "main" java.lang.RuntimeException: io.unitycatalog.client.ApiException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.unitycatalog.client.model.TableType`, problem: Unexpected value 'VIEW'

```

**Expected behavior**
Listing with Views, Materialized views etc. or fail silently or ** unsupported object type **

**System [please complete the following information]:**

Server: Azure Databricks 
Client: Mac OS
**Additional context**

Stack traceback:
```
Exception in thread "main" java.lang.RuntimeException: io.unitycatalog.client.ApiException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.unitycatalog.client.model.TableType`, problem: Unexpected value 'VIEW'
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 96] (through reference chain: io.unitycatalog.client.model.ListTablesResponse["tables"]->java.util.ArrayList[0]->io.unitycatalog.client.model.TableInfo["table_type"])
	at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:98)
Caused by: io.unitycatalog.client.ApiException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.unitycatalog.client.model.TableType`, problem: Unexpected value 'VIEW'
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 96] (through reference chain: io.unitycatalog.client.model.ListTablesResponse["tables"]->java.util.ArrayList[0]->io.unitycatalog.client.model.TableInfo["table_type"])
	at io.unitycatalog.client.api.TablesApi.listTablesWithHttpInfo(TablesApi.java:352)
	at io.unitycatalog.client.api.TablesApi.listTables(TablesApi.java:317)
	at io.unitycatalog.cli.TableCli.listTables(TableCli.java:124)
	at io.unitycatalog.cli.TableCli.handle(TableCli.java:45)
	at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:82)
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.unitycatalog.client.model.TableType`, problem: Unexpected value 'VIEW'
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 96] (through reference chain: io.unitycatalog.client.model.ListTablesResponse["tables"]->java.util.ArrayList[0]->io.unitycatalog.client.model.TableInfo["table_type"])
	at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2014)
	at com.fasterxml.jackson.databind.DeserializationContext.handleInstantiationProblem(DeserializationContext.java:1426)
	at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:205)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:246)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:310)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3893)
	at io.unitycatalog.client.api.TablesApi.listTablesWithHttpInfo(TablesApi.java:347)
	... 4 more
Caused by: java.lang.IllegalArgumentException: Unexpected value 'VIEW'
	at io.unitycatalog.client.model.TableType.fromValue(TableType.java:60)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.callOnWith(AnnotatedMethod.java:118)
	at com.fasterxml.jackson.databind.deser.std.FactoryBasedEnumDeserializer.deserialize(FactoryBasedEnumDeserializer.java:194)
	... 17 more
```

**Comment by epilif1017a** [comment]
Similar issue here. When doing `select * from a_view`, from Apache Spark 3.5.4 connected to UC through 0.2.1 connector, I get: 

io.unitycatalog.client.ApiException: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.unitycatalog.client.model.TableType`, problem: Unexpected value 'VIEW'

Packages:
org.apache.hadoop:hadoop-aws:3.3.4,
io.delta:delta-spark_2.12:3.3.0,
io.unitycatalog:unitycatalog-spark_2.12:0.2.1

**Comment by jhonatansosa-avinode** [comment]
Same issue for me when working with MANAGED_SHALLOW_CLONE:

`Cannot construct instance of io.unitycatalog.client.model.TableType, problem: Unexpected value 'MANAGED_SHALLOW_CLONE'`

Packages:
        "org.apache.hadoop:hadoop-azure:3.3.4,"
        "org.apache.hadoop:hadoop-common:3.3.4,"
        "org.apache.hadoop:hadoop-client-runtime:3.3.4,"
        "io.delta:delta-spark_2.12:3.2.1,"
        "io.unitycatalog:unitycatalog-spark_2.12:0.2.1",

**Comment by ik8** [comment]
@roeap Is this planned to be resolved in the next versions ?
