### ISSUE TITLE
Unitycatalog and Spark in Docker Container

### ISSUE THREAD

**Issue by RsZootje** [unitycatalog/unitycatalog#705]
**Describe the bug**

I have currently the following setup with docker containers:
- unitycatalog container
- spark-master container
- spark-worker-1 container
- spark-worker-2 container

All the containers are in the same docker network and I've created a docker volume which points to etc/data folder where all the unitycatalog data is stored. Furthermore, I've followed the docs in how to use apache spark to work with unity catalog. I am able to connect to the catalog by running queries like `spark.sql("SHOW CATALOGS")` or `spark.sql("SHOW TABLES IN unity")`.

Whenever I want to interact with the data in the catalog and run queries like `spark.sql("DESCRIBE DETAIL unity.default.marksheet")`. I still see a nice result with the metadata of the table but It's also returning an error. Please see example below:

```
Traceback (most recent call last):
  File "/workspace/test.py", line 8, in <module>
    spark.sql("DESCRIBE DETAIL unity.default.marksheet").show(truncate=False)
  File "/venv/lib/python3.10/site-packages/pyspark/sql/session.py", line 1631, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
  File "/venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [DELTA_PATH_DOES_NOT_EXIST] file:/app/unitycatalog/etc/data/managed/unity/default/tables/marksheet doesn't exist, or is not a Delta table.;
DescribeDeltaDetailCommand
+- ResolvedTable io.unitycatalog.spark.UCSingleCatalog@10e36ede, default.marksheet, DeltaTableV2(org.apache.spark.sql.SparkSession@6c2eb2e2,file:/app/unitycatalog/etc/data/managed/unity/default/tables/marksheet,Some(CatalogTable(
Catalog: unity
Database: default
Table: marksheet
Created Time: Wed Jul 17 18:40:05 UTC 2024
Last Access: UNKNOWN
Created By: Spark 
Type: MANAGED
Provider: DELTA
Location: file:///app/unitycatalog/etc/data/managed/unity/default/tables/marksheet
Storage Properties: [key1=value1, key2=value2]
Schema: root
 |-- id: integer (nullable = false)
 |-- name: string (nullable = false)
 |-- marks: integer (nullable = true)
)),Some(default.marksheet),None,Map())
```

Also running queries like `spark.sql("SELECT * FROM default.marksheet LIMIT 5").show()` returns the following error:

```
Traceback (most recent call last):
  File "/workspace/test.py", line 9, in <module>
    spark.sql("SELECT * FROM default.marksheet LIMIT 5").show()
  File "/venv/lib/python3.10/site-packages/pyspark/sql/session.py", line 1631, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
  File "/venv/lib/python3.10/site-packages/py4j/java_gateway.py", line 1322, in __call__
    return_value = get_return_value(
  File "/venv/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: [DELTA_TABLE_NOT_FOUND] Delta table `default`.`marksheet` doesn't exist.
```

It feels like spark is looking for the location of the data path which is already mounted via a docker volume but this doesnt resolve the issue. I am curious if anyone has encountered this or if I am maybe forgetting something.

Thanks in advance!

**To Reproduce**

1. Build spark master image
2. Build spark worker image
3. Build unitycatalog image from dockerfile provided in current repos
4. Create docker compose file with unitycatalog, spark-worker-1, spark-worker-2 and spark-master. Put all the containers in the same docker network and create a docker volume mounted to etc/data folder. Make the volume also available on the spark containers
5. Create sparksession with following options: 
```
"spark.jars.packages": "io.delta:delta-spark_2.12:3.2.1,io.unitycatalog:unitycatalog-spark_2.12:0.2.0",
"spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension",
 "spark.sql.catalog.spark_catalog": "io.unitycatalog.spark.UCSingleCatalog",
"spark.sql.catalog.unity": "io.unitycatalog.spark.UCSingleCatalog",
"spark.sql.catalog.unity.uri": "http://unity-catalog:8080",
"spark.sql.catalog.unity.token": "",
"spark.sql.defaultCatalog": "unity",
```
6. Run following spark query:
`spark.sql("DESCRIBE DETAIL unity.default.marksheet")` or `spark.sql("SELECT * FROM default.marksheet LIMIT 5")`

**Expected behavior**

No error DELTA_PATH_DOES_NOT_EXIST or DELTA_TABLE_NOT_FOUND. I expect a dataframe with data of marksheet

**Comment by RsZootje** [comment]
Never mind I just now solved the issue by mounting the etc/data volume also on all the containers
