### ISSUE TITLE
Spark Structured Streaming is not supported - DELTA_UNSUPPORTED_SCHEMA_DURING_READ

### ISSUE THREAD

**Issue by ni-mi** [unitycatalog/unitycatalog#715]
**Describe the bug**

It seems that using Spark Structured Streaming from a managed table (that should support tead) to an external table (that should support read/write) - is not working.
It throws DELTA_UNSUPPORTED_SCHEMA_DURING_READ.
  
**To Reproduce**

1. Download and tar fresh copy of Spark 3.5.3
2. Start UC server
3. Start Spark with UC:
```
bin/spark-shell --name "local-uc-test" \
    --master "local[*]" \
    --packages "io.delta:delta-spark_2.12:3.2.1,io.unitycatalog:unitycatalog-spark_2.12:0.2.0" \
    --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" \
    --conf "spark.sql.catalog.spark_catalog=io.unitycatalog.spark.UCSingleCatalog" \
    --conf "spark.sql.catalog.unity=io.unitycatalog.spark.UCSingleCatalog" \
    --conf "spark.sql.catalog.unity.uri=http://localhost:8080" \
    --conf "spark.sql.catalog.unity.token=" \
    --conf "spark.sql.defaultCatalog=unity"
```
4. Create the external output table as follows:
`spark.sql("create table unity.default.output using delta  location '/Users/username/Downloads/TestTable' as select * from unity.default.marksheet limit 1")
`
5. Run a stream as follows:
`spark.readStream.format("delta").table("unity.default.marksheet").writeStream.format("delta").outputMode("append").option("checkpointLocation", "/Users/username/Downloads/TestTable").toTable("unity.default.output").awaitTermination`

We get an exception:
```
org.apache.spark.sql.delta.DeltaAnalysisException: [DELTA_UNSUPPORTED_SCHEMA_DURING_READ] Delta does not support specifying the schema at read time.
  at org.apache.spark.sql.delta.DeltaErrorsBase.specifySchemaAtReadTimeException(DeltaErrors.scala:1034)
  at org.apache.spark.sql.delta.DeltaErrorsBase.specifySchemaAtReadTimeException$(DeltaErrors.scala:1033)
  at org.apache.spark.sql.delta.DeltaErrors$.specifySchemaAtReadTimeException(DeltaErrors.scala:3382)
  at org.apache.spark.sql.delta.sources.DeltaDataSource.sourceSchema(DeltaDataSource.scala:78)
  at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:233)
  at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:118)
  at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:118)
  at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:36)
  at org.apache.spark.sql.execution.datasources.FindDataSourceTable.org$apache$spark$sql$execution$datasources$FindDataSourceTable$$getStreamingRelation(DataSourceStrategy.scala:274)
  at org.apache.spark.sql.execution.datasources.FindDataSourceTable$$anonfun$apply$2.applyOrElse(DataSourceStrategy.scala:307)
  at org.apache.spark.sql.execution.datasources.FindDataSourceTable$$anonfun$apply$2.applyOrElse(DataSourceStrategy.scala:278)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$2(AnalysisHelper.scala:170)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:170)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:168)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:32)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$4(AnalysisHelper.scala:175)
  at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren(TreeNode.scala:1216)
  at org.apache.spark.sql.catalyst.trees.UnaryLike.mapChildren$(TreeNode.scala:1215)
  at org.apache.spark.sql.catalyst.plans.logical.SubqueryAlias.mapChildren(basicLogicalOperators.scala:1676)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.$anonfun$resolveOperatorsDownWithPruning$1(AnalysisHelper.scala:175)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:323)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning(AnalysisHelper.scala:168)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsDownWithPruning$(AnalysisHelper.scala:164)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsDownWithPruning(LogicalPlan.scala:32)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning(AnalysisHelper.scala:99)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperatorsWithPruning$(AnalysisHelper.scala:96)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperatorsWithPruning(LogicalPlan.scala:32)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators(AnalysisHelper.scala:76)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.resolveOperators$(AnalysisHelper.scala:75)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.resolveOperators(LogicalPlan.scala:32)
  at org.apache.spark.sql.execution.datasources.FindDataSourceTable.apply(DataSourceStrategy.scala:278)
  at org.apache.spark.sql.execution.datasources.FindDataSourceTable.apply(DataSourceStrategy.scala:241)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$2(RuleExecutor.scala:222)
  at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
  at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
  at scala.collection.immutable.List.foldLeft(List.scala:91)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1(RuleExecutor.scala:219)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$execute$1$adapted(RuleExecutor.scala:211)
  at scala.collection.immutable.List.foreach(List.scala:431)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.execute(RuleExecutor.scala:211)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.org$apache$spark$sql$catalyst$analysis$Analyzer$$executeSameContext(Analyzer.scala:240)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$execute$1(Analyzer.scala:236)
  at org.apache.spark.sql.catalyst.analysis.AnalysisContext$.withNewAnalysisContext(Analyzer.scala:187)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:236)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.execute(Analyzer.scala:202)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.$anonfun$executeAndTrack$1(RuleExecutor.scala:182)
  at org.apache.spark.sql.catalyst.QueryPlanningTracker$.withTracker(QueryPlanningTracker.scala:89)
  at org.apache.spark.sql.catalyst.rules.RuleExecutor.executeAndTrack(RuleExecutor.scala:182)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:223)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:330)
  at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:222)
  at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:77)
  at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:138)
  at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$2(QueryExecution.scala:219)
  at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
  at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:219)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
  at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:218)
  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:77)
  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:74)
  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:66)
  at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:91)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:89)
  at org.apache.spark.sql.streaming.DataStreamReader.table(DataStreamReader.scala:316)
  ... 47 elided
```

**Expected behavior**
The strram should work :) 

**System [please complete the following information]:**

-   OS: Mac OS Sonoma [14.7.1 (23H222)]

**Additional context**
AFAIK this should be working from 0.2.0 - as we support read from managed tables and read/write of external tables - and it seems that write to external tables using structured streaming is not working...

**Comment by tdas** [comment]
ohh this is very surprising. Its a funny Delta error, and I am not sure immediately what is going one. The error indicates that the schema was specified for the source, but the query you provided does not specify the schema.

Is it possible to give us a self-contained, minimal example project (sbt/maven project?) or full sequence of shell commands (e.g., that creates all the tables, in your snippet) from scratch that can help us repro the error?

**Comment by ni-mi** [comment]
@tdas I used the built in tables in the oss uc catalog that are created by default in the example I wrote above in the bug description so in zero setup you can reproduce it.

**Comment by jaceklaskowski** [comment]
take

**Comment by jaceklaskowski** [comment]
@tdas You're correct. "the schema was specified for the source, but the query you provided does not specify the schema." is the issue that I could reproduce myself and am digging deeper now.

**Comment by tdas** [comment]
thank you @jaceklaskowski please let us know what you find. 
i can imagine that there is some bug somewhere in the spark integration thats related to streaming because streaming may not have been tested as extensive as batch. pinging @cloud-fan in case he has some quick insights here about the spark integration.

**Comment by tdas** [comment]
Heu @jaceklaskowski any insights?

**Comment by jaceklaskowski** [comment]
Nothing yet. Just looked at the query plan in the stack trace and `FindDataSourceTable` and `UnresolvedTable` in particular that caught my attention. 

Having a look at it again over the weekend...Finally some free time! 😉

**Comment by jaceklaskowski** [comment]
What's interesting (and something I couldn't explain) is that for every use of `UnresolvedCatalogRelation` in `FindDataSourceTable`, a streaming relation gets `extraOptions`, and that's where this schema is coming from.

**Comment by jaceklaskowski** [comment]
Just found out that the following query is enough to reproduce the issue:

```scala
spark.readStream.format("delta").table("unity.default.marksheet")
```

This is with Spark 3.5.3 and Unity Catalog 0.3.0-SNAPSHOT.

**Comment by jaceklaskowski** [comment]
The difference between streaming queries with and without Unity Catalog is a `CatalogTable` with `schema` filled out for a Unity Catalog table.

**Comment by ni-mi** [comment]
@jaceklaskowski Do you know who is populating that? The connector probably is not the one to set the logic of populating the schema for structured streaming vs not structured streaming - it should be neutral to what API populated it...

**Comment by jaceklaskowski** [comment]
This happens in https://github.com/unitycatalog/unitycatalog/blob/ddf5496d6c0db0e2bc8cd1bb950d641a4fadde69/connectors/spark/src/main/scala/io/unitycatalog/spark/UCSingleCatalog.scala#L283.

And this is what happens when you call Delta Lake with no UC in-between https://github.com/delta-io/delta/blob/d970fed5eaf4a156ae1b977c25c52070d14cae60/spark/src/main/scala/org/apache/spark/sql/delta/catalog/DeltaCatalog.scala#L223

And I'm afraid I won't go any further than this without @tdas's or @cloud-fan's help. It'd be super helpful to talk to @cloud-fan who was on both sides of this integration (and knows a lot about Spark SQL's query execution, UC and Delta Lake).

**Comment by cloud-fan** [comment]
Hi @jaceklaskowski , how did you create `marksheet` in non-UC? I have no idea why the schema becomes empty without UC.

**Comment by cloud-fan** [comment]
Hi @ni-mi , have you tried it with HMS before? I don't see a difference between UC and HMS for this case, does it ever work?

**Comment by cloud-fan** [comment]
OK, I've figured it out now. This is a long-standing issue in Delta Lake, that the Delta table must have an empty schema in the catalog.

Delta Lake always sets the table schema to empty before saving the table into the catalog. However, the default table in UC does not keep the schema empty, and then we hit this issue. Databricks is fine as its Spark fork has a workaround for it.

If you don't use the default table in UC but create tables via Spark manually, you won't hit an issue, see https://github.com/unitycatalog/unitycatalog/pull/769

I think the right fix is to relax the check in Delta Lake here: https://github.com/delta-io/delta/blob/4d2c5cfd45119d78a86560de12e7b946228d77f2/spark/src/main/scala/org/apache/spark/sql/delta/sources/DeltaDataSource.scala#L78 
It's fine to have the specified schema, as it may come from the table metadata, as long as the schema is the same as the actual delta table schema.

cc @tdas @jaceklaskowski

**Comment by ni-mi** [comment]
@cloud-fan thanks! 
So the fix have to be in delta lake - and we need to wait for it's next release?

**Comment by cloud-fan** [comment]
I'm fixing it at https://github.com/delta-io/delta/pull/3929 , hopefully we can ship it with Delta 3.3.

**Comment by ni-mi** [comment]
That's great, thanks!

בתאריך יום ו׳, 6 בדצמ׳ 2024, 06:48, מאת Wenchen Fan ‏<
***@***.***>:

**Comment by arturowczarek** [comment]
@cloud-fan, I've followed up on your fix with https://github.com/delta-io/delta/pull/4550. I've also improved your initial test to properly illustrate the case https://github.com/unitycatalog/unitycatalog/pull/1003. To test it, you have to:
- Remove the `@Disabled` in front of the improved Unity Catalog test to see it is broken
- Fetch my delta fix
- Publish delta locally (`sbt publishLocal`)
- Bump the version in `build.sbt` to see it is fixed

Your commit https://github.com/unitycatalog/unitycatalog/pull/1003/commits/2df0989eebd97a1be1a11ccce169a02c63e5887e is not signed off. Can you fix it?

I've added publishing JUnit tests reports to artifacts in GitHub. I had some problems with tests (I confused `@Disable` with `@Ignore` in Junit and couldn't catch that my test was actually being run) and couldn't locate the problem, because the output is crammed with errors. Can I leave it in this pull request? It may be helpful for others.

@tdas, I'd appreciate if you could also have a look.
