### ISSUE TITLE
[CLI] NullPointerException when help option used with an invalid command

### ISSUE THREAD

**Issue by jaceklaskowski** [unitycatalog/unitycatalog#720]
When `--help` is executed with a non-existent command, `NullPointerException` is thrown.

```console
./bin/uc non_existent_command --help
Please provide a valid sub-command for non_existent_command.
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "entityOptions" is null
	at io.unitycatalog.cli.utils.CliUtils.printEntityHelp(CliUtils.java:574)
	at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:70)
```

```console
$ ./bin/uc --version
0.3.0-SNAPSHOT
```

**Comment by vksx** [comment]
take
