### ISSUE TITLE
Trino Integration: Trino and Unity Catalog use the same default port

### ISSUE THREAD

**Issue by avriiil** [unitycatalog/unitycatalog#739]
**Describe the bug**

AFAICT Trino and UC use the same default port number when launched locally: 8080.
If you launch UC first, then Trino then the docker run fails and the duplicate port number is obvious.
However, if you launch Trino first then UC then the UC server spins up without an error but then we are not able to access any of the entities. 

If UC is switching ports then it would perhaps be helpful to make that explicit.

**To Reproduce**

1. Launch Trino in local Docker container with `docker run --name trino -d -p 8080:8080 trinodb/trino`
2. Launch UC server
3. Run any entity command, e.g. `uc/bin catalog list`

Output:

```
Exception in thread "main" java.lang.RuntimeException: io.unitycatalog.client.ApiException: java.io.IOException: HTTP/1.1 header parser received no bytes
	at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:171)
Caused by: io.unitycatalog.client.ApiException: java.io.IOException: HTTP/1.1 header parser received no bytes
	at io.unitycatalog.client.api.CatalogsApi.listCatalogsWithHttpInfo(CatalogsApi.java:366)
	at io.unitycatalog.client.api.CatalogsApi.listCatalogs(CatalogsApi.java:333)
	at io.unitycatalog.cli.CatalogCli.listCatalogs(CatalogCli.java:78)
	at io.unitycatalog.cli.CatalogCli.handle(CatalogCli.java:39)
	at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:127)
Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
	at java.net.http/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:969)
	at java.net.http/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
	at io.unitycatalog.client.api.CatalogsApi.listCatalogsWithHttpInfo(CatalogsApi.java:348)
	... 4 more
Caused by: java.io.IOException: HTTP/1.1 header parser received no bytes
	at java.net.http/jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Utils.java:440)
	at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Http1Response.java:590)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Http1AsyncReceiver.java:302)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:268)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:182)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.io.EOFException: EOF reached while reading
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Http1AsyncReceiver.java:601)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:648)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:853)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:207)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:280)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:233)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:782)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:965)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:1476)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:1421)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:1421)
```

OR

```
Exception in thread "main" java.lang.RuntimeException: io.unitycatalog.client.ApiException: listCatalogs call failed with: 404 - Error 404 Not Found: HTTP 404 Not Found
	at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:171)
Caused by: io.unitycatalog.client.ApiException: listCatalogs call failed with: 404 - Error 404 Not Found: HTTP 404 Not Found
	at io.unitycatalog.client.api.CatalogsApi.getApiException(CatalogsApi.java:77)
	at io.unitycatalog.client.api.CatalogsApi.listCatalogsWithHttpInfo(CatalogsApi.java:356)
	at io.unitycatalog.client.api.CatalogsApi.listCatalogs(CatalogsApi.java:333)
	at io.unitycatalog.cli.CatalogCli.listCatalogs(CatalogCli.java:78)
	at io.unitycatalog.cli.CatalogCli.handle(CatalogCli.java:39)
	at io.unitycatalog.cli.UnityCatalogCli.main(UnityCatalogCli.java:127)
```

**Expected behavior**

Get list of catalogs

**System [please complete the following information]:**

-   OS: MacOS 14.3.1

**Comment by avriiil** [comment]
Yes, I can get things working by running Trino on another port. My intention with creating the issue was to flag the case when someone spins up Trino first, and then encounters the mysterious errors :)
