### ISSUE TITLE
java.nio.file.AccessDeniedException: etc/conf/public_key.der

### ISSUE THREAD

**Issue by MammadTavakoli** [unitycatalog/unitycatalog#755]
when I run `docker compose up ` the following error is occurred:

```
server-1  | Exception in thread "main" java.nio.file.AccessDeniedException: etc/conf/public_key.der
server-1  | at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
server-1  | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
server-1  | at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
server-1  | at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
server-1  | at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
server-1  | at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
server-1  | at java.base/java.nio.file.Files.write(Files.java:3512)
server-1  | at io.unitycatalog.server.security.SecurityConfiguration.initializeIfMissing(SecurityConfiguration.java:61)
server-1  | at io.unitycatalog.server.security.SecurityConfiguration.<init>(SecurityConfiguration.java:48)
server-1  | at io.unitycatalog.server.UnityCatalogServer.<init>(UnityCatalogServer.java:67)
server-1  | at io.unitycatalog.server.UnityCatalogServer.main(UnityCatalogServer.java:197)
server-1 exited with code 1
```

how can solve the problem?

**Comment by pedroivobr** [comment]
To resolve the issue, simply modify line 2 of the Dockerfile related to the server to correctly set the HOME directory path:
```dockerfile
ARG HOME="/home/unitycatalog"`
``` 
After that, just run docker-compose again, and it will work as expected.
