### ISSUE TITLE
Functions not working with local spark and unitycatalog setup.

### ISSUE THREAD

**Issue by kshitiz-suman** [unitycatalog/unitycatalog#783]
**Describe the bug**

I was trying to use unitycatalog with pyspark on my local machine. I used this doc ( https://docs.unitycatalog.io/integrations/unity-catalog-spark/ ) for setting it up on my laptop. I am creating catalogs, schemas and functions using the REST API endpoint and then running  

```spark.conf.set("spark.sql.catalog.postman_catalog1", "io.unitycatalog.spark.UCSingleCatalog")
spark.conf.set("spark.sql.catalog.postman_catalog1.uri", "http://localhost:8080/")
spark.conf.set("spark.sql.catalog.postman_catalog1.token", "")
```
in pyspark shell to run SQL Queries. I have registered a function with 
```
{
    "name": "postman_func1",
    "catalog_name": "postman_catalog1",
    "schema_name": "postman_db1",
    "full_name": "postman_catalog1.postman_db1.postman_func1"
 }
 ```
 I am trying to use the function in spark SQL 
 `spark.sql("SELECT postman_catalog1.postman_db1.postman_func1('abcd')").show()` 
 but it throws 
 ```
 Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kshitizsuman/scripts/virtualenvs/spark_3_5_3/lib/python3.10/site-packages/pyspark/sql/session.py", line 1631, in sql
    return DataFrame(self._jsparkSession.sql(sqlQuery, litArgs), self)
  File "/Users/kshitizsuman/scripts/virtualenvs/spark_3_5_3/lib/python3.10/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/Users/kshitizsuman/scripts/virtualenvs/spark_3_5_3/lib/python3.10/site-packages/pyspark/errors/exceptions/captured.py", line 185, in deco
    raise converted from None
pyspark.errors.exceptions.captured.AnalysisException: Catalog postman_catalog1 does not support functions.
```

Are functions not supported with the spark integration of unitycatalog ??

**To Reproduce**

1. Setup unitycatalog with pyspark on local machine.
2. Create a SQL function using REST API of unitycatalog ( `localhost:8080`)
3. Try to use the function in Spark SQL Query.

**System [please complete the following information]:**

-   Pyspark 3.5.3

**Comment by tdas** [comment]
Not yet. Apache Spark itself does not yet support having functions stored
in an external metastore. But I would love to see this be possible sometime
soon :)

**Comment by tdas** [comment]
Maybe I wasnt clear in my previous message. 
- UC server supports storing functions, and the UC rest APIs support create/read/update/list/delete operations on the functions.
- Any engine CAN use the UC REST APIs to operate on functions stored in UC. But that will first REQUIRE the engine to have the internal concept of functions that can be fetched from an external catalog. 
- Apache Spark does not fulfill the requirement yet. Yes, it has UDFs that can be defined and stored in its in-memory session catalog. But it does not have the ability to store and fetch functions from external catalogs like Hive, etc. 

- Until Apache Spark adds that internal ability, the UC-Spark integration in this project cannot integrated UC-stored functions with Apache Spark.

**Comment by mmmmkkkk0000** [comment]
هلو
