### ISSUE TITLE
S3 bucket configuration not found.

### ISSUE THREAD

**Issue by mantovani** [unitycatalog/unitycatalog#805]
**Describe the bug**

I've created a simple table with external storage in S3. However when I try to retrieve data I get:

{
    "error_code": "FAILED_PRECONDITION",
    "details": [
        {
            "reason": "FAILED_PRECONDITION",
            "metadata": {},
            "@type": "google.rpc.ErrorInfo"
        }
    ],
    "stack_trace": null,
    "message": "S3 bucket configuration not found."
}

Based on the documentation the name of the bucket should match the bucket in the etc/conf/server.properties.

```
server.env=false
## Identity Provider authorization parameters
# examples:
# authorization=enable
# authorization-url=https://accounts.google.com/o/oauth2/auth
# token-url=https://oauth2.googleapis.com/token
# client-id=111122223333-abab1212cdcd3434.apps.googleusercontent.com
# client-secret=GOCSPX-ababfoobarcdcd-5q
server.authorization=disable
server.authorization-url=
server.token-url=
server.client-id=
server.client-secret=
server.redirect-port=
# D-Days H-Hours M-Minutes S-Seconds (P5D = 5 days,PT5H = 5 hours, PT5M = 5 minutes, PT5S = 5 seconds)
server.cookie-timeout=P5D

# Define the model storage root.  Cloud storage or file based allowed.
# If no root specified, the current working directory of the server is used.

#storage-root.models=s3://my-s3-bucket/root
#storage-root.models=abfs://file_system@account_name.dfs.core.windows.net/root
#storage-root.models=gs://my-gc-bucket/root
storage-root.models=s3://foo/root

## S3 Storage Config (Multiple configs can be added by incrementing the index)
s3.bucketPath.0="s3://foo"
s3.region.0=us-east-2
#s3.awsRoleArn.0=
# Optional (If blank, it will use DefaultCredentialsProviderChain)
s3.accessKey.0=...
s3.secretKey.0=...
# Test Only (If you provide a session token, it will just use those session creds, no downscoping)
#s3.sessionToken.0=

## ADLS Storage Config (Multiple configs can be added by incrementing the index)
adls.storageAccountName.0=
adls.tenantId.0=
adls.clientId.0=
adls.clientSecret.0=

## GCS Storage Config (Multiple configs can be added by incrementing the index)
gcs.bucketPath.0=
# Optional (If blank, it will use Default Application chain to find credentials)
gcs.jsonKeyFilePath.0=
```

**To Reproduce**

1. bin/uc table create --full_name unity.default.bar --columns "id INT, name STRING"  --storage_location s3://foo/bar
2. bin/uc volume read --full_name unity.default.bar

**Expected behavior**

Get the table data

**System [please complete the following information]:**

-   OSX

**Additional context**

**Comment by mantovani** [comment]
I just would like to know if I'm doing something wrong or is not supported yet.

**Comment by kamalkang-hpe** [comment]
Hi @mantovani - I was troubleshooting this issue and looks like you need to write data first, that is when the delta table gets created and then read it.
` 
bin/uc table write --full_name unity.default.bar
`

**Comment by mantovani** [comment]
@kamalkang-hpe I got exactly the same error when I try to write data:


```
➜  unitycatalog-0.2.1 bin/uc table create --full_name unity.default.issue805 --columns "id INT, name STRING"  --storage_location s3://foo/issue805
┌───────────────────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                KEY                │                                                                             VALUE                                                                             │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│NAME                               │issue805                                                                                                                                                       │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│CATALOG_NAME                       │unity                                                                                                                                                          │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│SCHEMA_NAME                        │default                                                                                                                                                        │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│TABLE_TYPE                         │EXTERNAL                                                                                                                                                       │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│DATA_SOURCE_FORMAT                 │DELTA                                                                                                                                                          │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│COLUMNS                            │{"name":"id","type_text":"int","type_json":"{\"name\":\"id\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}}","type_name":"INT","type_precision":0,"typ│
│                                   │e_scale":0,"type_interval_type":null,"position":0,"comment":null,"nullable":true,"partition_index":null}                                                       │
│                                   │{"name":"name","type_text":"string","type_json":"{\"name\":\"name\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}}","type_name":"STRING","type_precisio│
│                                   │n":0,"type_scale":0,"type_interval_type":null,"position":1,"comment":null,"nullable":true,"partition_index":null}                                              │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│STORAGE_LOCATION                   │s3://foo/issue805                                                                                                                                        │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│COMMENT                            │null                                                                                                                                                           │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│PROPERTIES                         │{}                                                                                                                                                             │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│OWNER                              │null                                                                                                                                                           │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│CREATED_AT                         │1734978522552                                                                                                                                                  │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│CREATED_BY                         │null                                                                                                                                                           │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│UPDATED_AT                         │1734978522552                                                                                                                                                  │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│UPDATED_BY                         │null                                                                                                                                                           │
├───────────────────────────────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│TABLE_ID                           │96a48152-d3dc-4b92-b3d5-6f08bbadf940                                                                                                                           │
└───────────────────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

```
➜  unitycatalog-0.2.1 bin/uc table write --full_name unity.default.issue805 ""
Error occurred while executing the command. Failed to write sample data to delta table s3://foo/issue805generateTemporaryTableCredentials call failed with: 400 - {"error_code":"FAILED_PRECONDITION","details":[{"reason":"FAILED_PRECONDITION","metadata":{},"@type":"google.rpc.ErrorInfo"}],"stack_trace":null,"message":"S3 bucket configuration not found."}
```


```
➜  unitycatalog-0.2.1 cat etc/conf/server.properties
server.env=false
## Identity Provider authorization parameters
# examples:
# authorization=enable
# authorization-url=https://accounts.google.com/o/oauth2/auth
# token-url=https://oauth2.googleapis.com/token
# client-id=111122223333-abab1212cdcd3434.apps.googleusercontent.com
# client-secret=GOCSPX-ababfoobarcdcd-5q
server.authorization=disable
server.authorization-url=
server.token-url=
server.client-id=
server.client-secret=
server.redirect-port=
# D-Days H-Hours M-Minutes S-Seconds (P5D = 5 days,PT5H = 5 hours, PT5M = 5 minutes, PT5S = 5 seconds)
server.cookie-timeout=P5D

# Define the model storage root.  Cloud storage or file based allowed.
# If no root specified, the current working directory of the server is used.

storage-root.models=s3://foo/root

## S3 Storage Config (Multiple configs can be added by incrementing the index)
s3.bucketPath.0="s3://foo"
s3.region.0=us-east-2
#s3.awsRoleArn.0=
# Optional (If blank, it will use DefaultCredentialsProviderChain)
s3.accessKey.0=""
s3.secretKey.0=""
# Test Only (If you provide a session token, it will just use those session creds, no downscoping)
#s3.sessionToken.0=

## ADLS Storage Config (Multiple configs can be added by incrementing the index)
adls.storageAccountName.0=
adls.tenantId.0=
adls.clientId.0=
adls.clientSecret.0=

## GCS Storage Config (Multiple configs can be added by incrementing the index)
gcs.bucketPath.0=
# Optional (If blank, it will use Default Application chain to find credentials)
gcs.jsonKeyFilePath.0=
```

**Comment by kamalkang-hpe** [comment]
Hi Hi @mantovani - This is the command
`unitycatalog-0.2.1 bin/uc table write --full_name unity.default.issue805`

**Comment by Delphin1** [comment]
Hi!
I have the same behavior. I have tried versions 0.2.0 and 0.2.1 and several buckets with keys and via role. 

`{
  "error_code": "FAILED_PRECONDITION",
  "details": [
    {
      "reason": "FAILED_PRECONDITION",
      "metadata": {},
      "@type": "google.rpc.ErrorInfo"
    }
  ],
  "stack_trace": null,
  "message": "S3 bucket configuration not found."
}`

**Comment by mantovani** [comment]
> Hi @mantovani - This is the command `unitycatalog-0.2.1 bin/uc table write --full_name unity.default.issue805`

Even a simple create external table isn't working.

```
create table demo_table2 (id int, desc string) using delta location "s3://my-s3-bucket/demo_table";
```

```
25/01/04 17:49:33 ERROR SparkSQLDriver: Failed in [ create table demo_table2 (id int, desc string) using delta location "s3://my-s3-bucket/demo_table"]
io.unitycatalog.client.ApiException: generateTemporaryPathCredentials call failed with: 400 - {"error_code":"FAILED_PRECONDITION","details":[{"reason":"FAILED_PRECONDITION","metadata":{},"@type":"google.rpc.ErrorInfo"}],"stack_trace":null,"message":"S3 bucket configuration not found."}
	at io.unitycatalog.client.api.TemporaryCredentialsApi.getApiException(TemporaryCredentialsApi.java:78)
	at io.unitycatalog.client.api.TemporaryCredentialsApi.generateTemporaryPathCredentialsWithHttpInfo(TemporaryCredentialsApi.java:192)
	at io.unitycatalog.client.api.TemporaryCredentialsApi.generateTemporaryPathCredentials(TemporaryCredentialsApi.java:170)
	at io.unitycatalog.spark.UCSingleCatalog.createTable(UCSingleCatalog.scala:106)
	at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:44)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:220)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:691)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:682)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:713)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:744)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:651)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:68)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:501)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1(SparkSQLCLIDriver.scala:619)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1$adapted(SparkSQLCLIDriver.scala:613)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processLine(SparkSQLCLIDriver.scala:613)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:310)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
generateTemporaryPathCredentials call failed with: 400 - {"error_code":"FAILED_PRECONDITION","details":[{"reason":"FAILED_PRECONDITION","metadata":{},"@type":"google.rpc.ErrorInfo"}],"stack_trace":null,"message":"S3 bucket configuration not found."}
io.unitycatalog.client.ApiException: generateTemporaryPathCredentials call failed with: 400 - {"error_code":"FAILED_PRECONDITION","details":[{"reason":"FAILED_PRECONDITION","metadata":{},"@type":"google.rpc.ErrorInfo"}],"stack_trace":null,"message":"S3 bucket configuration not found."}
	at io.unitycatalog.client.api.TemporaryCredentialsApi.getApiException(TemporaryCredentialsApi.java:78)
	at io.unitycatalog.client.api.TemporaryCredentialsApi.generateTemporaryPathCredentialsWithHttpInfo(TemporaryCredentialsApi.java:192)
	at io.unitycatalog.client.api.TemporaryCredentialsApi.generateTemporaryPathCredentials(TemporaryCredentialsApi.java:170)
	at io.unitycatalog.spark.UCSingleCatalog.createTable(UCSingleCatalog.scala:106)
	at org.apache.spark.sql.execution.datasources.v2.CreateTableExec.run(CreateTableExec.scala:44)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result$lzycompute(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.result(V2CommandExec.scala:43)
	at org.apache.spark.sql.execution.datasources.v2.V2CommandExec.executeCollect(V2CommandExec.scala:49)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:107)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:98)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(origin.scala:76)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:461)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:32)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:437)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:98)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:85)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:83)
	at org.apache.spark.sql.Dataset.<init>(Dataset.scala:220)
	at org.apache.spark.sql.Dataset$.$anonfun$ofRows$2(Dataset.scala:100)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:97)
	at org.apache.spark.sql.SparkSession.$anonfun$sql$4(SparkSession.scala:691)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:682)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:713)
	at org.apache.spark.sql.SparkSession.sql(SparkSession.scala:744)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:651)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:68)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:501)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1(SparkSQLCLIDriver.scala:619)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.$anonfun$processLine$1$adapted(SparkSQLCLIDriver.scala:613)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processLine(SparkSQLCLIDriver.scala:613)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:310)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:1029)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:194)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:217)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:91)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1120)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1129)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by jayhan94** [comment]
Hi, I met this error too and this is the reproduce procedure: https://github.com/jayhan94/MiniLake

**Comment by andormarkus** [comment]
Hi Everybody,

I was not able to reproduce the error. Here's my setup and testing process:

1. Created two AWS IAM roles:
**Role 1: unitycatalog-iamrole-dev**

Trust policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Service": "ec2.amazonaws.com"
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

IAM policy:
```json
{
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Effect": "Allow",
            "Resource": "arn:aws:iam::123456789012:role/unitycatalog-vended-iamrole-dev"
        }
    ],
    "Version": "2012-10-17"
}
```


**Role 2: unitycatalog-vended-iamrole-dev**
Trust policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "arn:aws:iam::123456789012:role/unitycatalog-iamrole-dev"
                ]
            },
            "Action": "sts:AssumeRole"
        }
    ]
}
```

IAM policy:
```json
{
    "Statement": [
        {
            "Action": "s3:*",
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::example-sandbox-bucket"
        }
    ],
    "Version": "2012-10-17"
}
```

2. Environment setup:

 - Launched an EC2 instance with Amazon Linux 2023
 - Installed Docker and Docker Compose
 - Cloned the latest main branch

```bash
git clone https://github.com/unitycatalog/unitycatalog.git
cd unitycatalog
```

3. Configuration: Modified `etc/conf/server.properties` with:

```properties
s3.bucketPath.0=s3://example-sandbox-bucket
s3.region.0=eu-central-1
s3.awsRoleArn.0=arn:aws:iam::123456789012:role/unitycatalog-vended-iamrole-dev
```


4. Deployment and testing:
```bash 
docker compose up --detach
docker exec -it unitycatalog-server-1 /bin/bash
```

5. Successfully executed:
```bash
bin/uc table create --full_name unity.default.issue805 --columns "id INT, name STRING" --storage_location s3://example-sandbox-bucket/test/deltalake/issue805
bin/uc table write --full_name unity.default.issue805 "1,one"
```

**Comment by saiakhiltummala** [comment]
I am able to reproduce it and getting the same error. Tried multiple ways. Used windows and linux machines but still getting the error of S3 config not found. Added the required data in etc/conf/server.properties
UnityCatalog@Test1:~/unitycatalog$ bin/uc table read  --full_name unity.default.unitydemo2025
Error occurred while executing the command. Failed to read delta table s3://unitydemo2025generateTemporaryTableCredentials call failed with: 400 - {"error_code":"FAILED_PRECONDITION","details":[{"reason":"FAILED_PRECONDITION","metadata":{},"@type":"google.rpc.ErrorInfo"}],"stack_trace":null,"message":"S3 bucket configuration not found."}

**Comment by saiakhiltummala** [comment]
HI @jayhan94  @andormarkus 
Did you ever get this issue?

UnityCatalog@Test1:~/unitycatalog$ bin/uc table read  --full_name unity.default.unitydemo2025
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Error occurred while executing the command. Failed to read delta table s3://unitydemo2025/Failed to read delta table
2025-02-07T12:11:36.464886292Z shutdown-hook-0 WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger


I did multiple checks and still getting this issue

**Comment by jonathan5p** [comment]
Not sure if this can work for you @mantovani, but in my case the problem was in the `compose.yaml` file. By default the `compose.yaml` file copies the configuration you have on `./etc/conf` to `/opt/unitycatalog/etc/conf`, but the Server tries to read from `/home/unitycatalog/etc/conf`. I just change that section in my compose file and know everything is working as it should. Not sure if this is intended or if it is a bug. 

This is how the new section looks like:

``` bash
  server:
    image: unitycatalog/unitycatalog:latest
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./etc/conf
        target: /home/unitycatalog/etc/conf
```
